### ISSUE TITLE
Irregular shape of BEV

### ISSUE THREAD

**Issue by UditSinghParihar** [autonomousvision/neat#13]
Hi @kashyap7x , thanks for your wonderful work on NEAT. I would like to ask regarding the blobby nature of BEV output as compared to other BEV methods like LSS or Fiery, where BEV of vehicles is quite sharp. Can you tell some pointers on how we can improve this irregular vehicle bev coming in NEAT?

![image](https://user-images.githubusercontent.com/34499128/204053542-53743c89-5b46-4a4e-b4cb-eb962202ca28.png)

Thanks

**Comment by kashyap7x** [comment]
Hello!

Since the BEV segmentation was an auxiliary task, we did not focus on improving its sharpness in the paper. Some ideas which I think could help include using multi-resolution feature grids instead of simple feature vectors for conditioning, a better initialization of the attention weights than uniform (using information about the camera matrix), and removing future points from the semantics to simplify the task. Another simple thing to try would be tuning the weights of the semantic loss, and maybe setting class-specific weights.

In addition, implicit semantic segmentation has progressed significantly since early 2021, and some ideas from current state-of-the-art papers could be incorporated to sharpen the NEAT semantics, e.g.,
1. [Panoptic Neural Fields: A Semantic Object-Aware Neural Scene Representation](https://arxiv.org/abs/2205.04334)
2. [Semantic Scene Completion using Local Deep Implicit Functions on LiDAR Data](https://arxiv.org/abs/2011.09141)
